name       : lttoolbox
version    : 3.3.3
release    : 1
source     :
    - http://iweb.dl.sourceforge.net/project/apertium/lttoolbox/3.3/lttoolbox-3.3.3.tar.gz : 5ccfc98bd71e1c9cbb952f3b01a6f615cf580f39ce74cdcb7221fc9b48f40617
license    : GPL-2.0
component  : programming.tools
summary    : Translation tools used by apertium
description: |
    Translation tools used by apertium
builddeps  :
    - gcc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
